### PR TITLE
Moved ability details into a configuration file

### PR DESCRIPTION
**Pull request by chirophobic**
To help with future development and assist with extensibility, I thought it would be really helpful to move the ability config from the top of the main file into a `config.py` file.

I initially considered using JSON files for the configuration. However, you can't add comments to JSON files. I also considered using YAML because it's equally easy to use and does include comments. The problem with YAML is that it isn't supported natively by Python and would require a package to be downloaded/installed. I figured that to make contributing and running the project as easy as possible we should keep the setup process to a minimum.

I must admit that I'm not a RuneScape veteran, so I don't really know what most of the ability properties are. I've done my best to extract the abilities out and leave the main file untouched and still working.

I've put together an outline on how abilities should be structured in the `config.py` file. It is as follows:

```
ABILITIES = [
    {
        'name': '<ability name>',
        'cooldown': <number>, # Number of seconds that the ability goes on cooldown for
        'type': '<ultimate | threshold | basic>',
        'damage': <number>, # Set to zero for no on-hit damage
        'time': <number>, # How long an ability takes to use in seconds
        'debilitating': <True | False>, # Whether the abilities can stun or bind target
        'binds': <True | False>, # Whether the abilities can bind target,
        'punishing': <True | False>, # Whether the abilities does extra damage to targets that are stunned or bound
        'aoe': <True | False>,
        # Abilities that take longer than 1.8 seconds by default aren't affected by crit-boot. Use this to override.
        'crit_boost_affected': <True | False>,
        # Fill out these settings if it's a buffing ability
        'buff': {
            'time': <number>, # Duration of the buff in seconds
            'crit_boost': <True | False>, # Whether or not this ability buffs your crit-chance
            'multiplier': <number>, # Multiplier for boosted damage
        },
        # Fill out these settings if it's an ability that applies a bleed
        'bleed': {
            'time': <number>, # Duration of the bleed effect
            # Whether or not the first hit of this bleed is affected by damage modifying abilities 
            'first_hit_buffable': <True | False>,
        },
    }
```

Please do tell me if this is incorrect, not-satisfactory, not helpful, or what could be changes and/or improved.

### CODE REVIEW

**Comment by NightShadeI** [comment]
I really appreciate this work! there was something else I was currently working on (.csv file) so both the user could look over the values for their own use, and python works really well with them in terms of reading from them. What do you think of this idea? I am also happy to implement yours (or at least temporarily).

**Comment by chirophobic** [comment]
@NightShadeI I wouldn't mind having a look at your idea. Can you push your changes to a branch so I can take a look?

**Comment by NightShadeI** [comment]
For now it is probably just easier if I send an image since I haven't linked it with the code yet - but this is what I'm working on (while double checking my values).

https://imgur.com/a/8RJLf

**Comment by chirophobic** [comment]
@NightShadeI What you've got there is probably a better solution. I think it makes more sense.

**Pull request closed without merging**
